openapi: "3.0.1"
info:
  title: SumUp REST API
  version: 1.0.0
  contact:
    email: dev@sumup.com
servers:
  - url: https://api.sumup.com/{version}
    description: Production server
    variables:
      version:
        default: v0.1
        description: Version of the API.
tags:
  - name: Checkouts
    description: View and manage payment checkouts.
  - name: Customers
    description: View and manage saved customers and their payment instruments.
  - name: Transactions
    description: View transactions.
paths:
  /checkouts:
    get:
      description: Lists all checkout resources.
      tags:
        - Checkouts
      security:
        - accessToken:
          - payments
    post:
      description: Create a new payment checkout resource
      tags:
        - Checkouts
      security:
        - accessToken:
          - payments
  /checkouts/{id}:
    get:
      description: Retrieves an identified checkout resource.
      tags:
        - Checkouts
      security:
        - accessToken:
          - payments
    put:
      description: Processes an identified checkout resource with the specified payment instrument.
      tags:
        - Checkouts
      security:
        - accessToken:
          - payments
    delete:
      description: Deactivates an identified checkout resource.
      tags:
        - Checkouts
      security:
        - accessToken:
          - payments
  /customers:
    post:
      description: Creates a new saved customer resource.
      tags:
        - Customers
      security:
        - accessToken:
          - payment_instruments
  /customers/{customer_id}:
    get:
      description: Retrieves an identified saved customer resource.
      tags:
        - Customers
      security:
        - accessToken:
          - payment_instruments
    put:
      description: Updates an identified saved customer resource.
      tags:
        - Customers
      security:
        - accessToken:
          - payment_instruments
  /customers/{customer_id}/payment-instruments:
    get: # FIXME Add details of sepa dd response.
      description: Lists all active payment instrument resources that are saved for an identified customer.
      tags:
        - Customers
    post: # FIXME Add option of for sepa dd pi
      description: Creates and activates a new payment instrument resource for an identified customer.
      tags:
        - Customers
      security:
        - accessToken:
          - payment_instruments
  /customers/{customer_id}/payment-instruments/{token}:
    delete:
      description: Deactivates an identified card payment instrument resource for a customer.
      tags:
        - Customers
      security:
        - accessToken:
          - payment_instruments
  # # /customers/{customer_id}/payment-instruments/direct_debit:
    #   parameters:
    #     - $ref: "#/components/parameters/customerId"
    #   put:
    #     description:
    #     tags:
    #       - Customers
    #     security:
    #       - accessToken:
    #         - payment_instruments
    #     requestBody:
    #     responses:
    #       "200":
    #         $ref: "#/components/responses/FIXME"
    #       "400":
    #         $ref: "#/components/responses/errorBadRequest"
    #       "401":
    #         $ref: "#/components/responses/errorNotAuthorized"
    #       "403":
    #         $ref: "#/components/responses/errorForbidden"
    #       "404":
    #         $ref: "#/components/responses/errorNotFound"
    #   delete:
  /me/transactions/history:
    get:
      description: Lists a history of all transactions associated with the merchant account.
      tags:
        - Transactions
      security:
        - accessToken:
          - transactions.history
      # FIXME Add parameters/request body???
  /me/transactions:
    get:
      description: |
        Retrieves the full details of an identified transaction. The transaction is identified by a query parameter and at least one of following parameters is required:
         *  `id`
         *  `internal_id`
         *  `transaction_code`
      tags:
        - Transactions
      security:
        - accessToken:
          - transactions.history
security:
  - accessToken: []
components:
  # # foreignTransactionId:
    #   name: foreign_transaction_id
    #   in: query
    #   description: Retrieves the transaction resource with the specified external (foreign) transaction ID (the `id` parameter in the transaction resource).
    #   required:
    #   schema:
    #     type: string
    # clientTransactionIdTrx:
    #   name: client_transaction_id
    #   in: query
    #   description: Retrieves the transaction resource with the specified client transaction ID (the `client_transaction_id` parameter in the transaction resource).
    #   required:
    #   schema:
    #     type: string
    eventStatuses:
      name: event_statuses
      in: query
      description: Filters the returned transaction events in the transaction resource by the speficied transaction event statuses.
      required: false
      schema:
        type: array
        items:
          type: string
          enum: # FIXME List all possible values
            - FAILED
            - SUCCESSFUL
    eventTypes:
      name: event_types
      in: query
      description: Filters the returned transaction events in the transaction resource by specified transaction event types.
      required: false
      schema:
        type: array
        items:
          type: string
          enum:
            - PAYOUT
            - REFUND
            - CHARGE_BACK
            #- PAYOUT_DEDUCTION
  # # sepaDdCreateRequest:
    #   description: Details for creating a new SEPA Direct Debit mandate as a payment instrument.
    #   content:
    #     application/json:
    #       schema:
    #         - $ref: "#/components/schemas/sepaDetailsFull"
    # sepaDdUpdateRequest:
    #   description: Details for updating an existing SEPA Direct Debit mandate as a payment instrument.
    #   content:
    #     application/json:
    #       schema:
    #         - $ref: "#/components/schemas/sepaDetails"
    # customerDdRequest:
    #   # for sepaDD, the following fields are required:
    #   required:
    #     - customer_id
    #     - personal_details
    #       - first_name
    #       - last_name
    #       - phone
    #       - address
    #         - line1
    #         - line2
    #         - country
    #         - postal_code
    #         - city
    #         - state
  # examples:
  # headers:
  securitySchemes:
    accessToken:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://api.sumup.com/authorize
          tokenUrl: https://api.sumup.com/token
          refreshUrl: https://api.sumup.com/token
          scopes:
            payments: Make payments by creating and processing checkouts.
            transactions.history: View your transactions and transaction history.
            user.profile_readonly: View your user profile details.
            user.app-settings: View and manage the settings of your client application.
            balance: View and manage your payout balance.
          # # user.profile: View and manage your user profile
            # user.payout-settings: View and manage your payout settings
            # user.subaccounts: View and manage the user profile details of your employees
            # products: View and manage products, shelves, prices, and VAT rates
            # boleto: Process boleto checkouts
            # referrals.reports:
            # referrals.post:
            # referrals.payout:
            sepa_dd: Manage SEPA Direct Debit mandates for customers.
            payments_instruments: Manage customers and their payment instruments.
        clientCredentials:
          # authorizationUrl: https://api.sumup.com/authorize
          tokenUrl: https://api.sumup.com/token
          scopes:
            payments: Make payments by creating and processing checkouts.
            transactions.history: View your transactions and transaction history.
            # user.profile_readonly: View your user profile details.
            user.app-settings: View and manage the settings of your client application.
            balance: View and manage your payout balance.
          # # user.profile: View and manage your user profile
            # user.payout-settings: View and manage your payout settings
            # user.subaccounts: View and manage the user profile details of your employees
            # products: View and manage products, shelves, prices, and VAT rates
            # boleto: Process boleto checkouts
            # referrals.reports:
            # referrals.post:
            # referrals.payout:
            payments_instruments: Manage customers and their payment instruments.
  # links:
  # callbacks:
